version: 2.1

parameters:
  full-job:
    type: boolean
    default: false
  commandline-job:
    type: boolean
    default: false
  dev-jobs:
    type: boolean
    default: false
  gui-commons-job true:
    type: boolean
    default: false
  http-client-job true:
    type: boolean
    default: false
  lang-all:
    type: boolean
    default: false
  lang-ar-job:
    type: boolean
    default: false
  lang-ast-job:
    type: boolean
    default: false
  lang-be-job:
    type: boolean
    default: false
  lang-br-job:
    type: boolean
    default: false
  lang-ca-job:
    type: boolean
    default: false
  lang-da-job:
    type: boolean
    default: false
  lang-de-job:
    type: boolean
    default: false
  lang-de-simple-job: 
    type: boolean
    default: true
  lang-el-job:
    type: boolean
    default: false
  lang-en-job:
    type: boolean
    default: false
  lang-eo-job:
    type: boolean
    default: false
  lang-es-job:
    type: boolean
    default: false
  lang-fa-job:
    type: boolean
    default: false
  lang-fr-job:
    type: boolean
    default: false
  lang-ga-job:
    type: boolean
    default: false
  lang-gl-job:
    type: boolean
    default: false
  lang-is-job:
    type: boolean
    default: false
  lang-it-job:
    type: boolean
    default: false
  lang-ja-job:
    type: boolean
    default: false
  lang-km-job:
    type: boolean
    default: false
  lang-lt-job:
    type: boolean
    default: false
  lang-ml-job:
    type: boolean
    default: false
  lang-nl-job:
    type: boolean
    default: false
  lang-pl-job:
    type: boolean
    default: false
  lang-pt-job:
    type: boolean
    default: false
  lang-ro-job:
    type: boolean
    default: false
  lang-ru-job:
    type: boolean
    default: false
  lang-sk-job:
    type: boolean
    default: false
  lang-sl-job:
    type: boolean
    default: false
  lang-sr-job:
    type: boolean
    default: false
  lang-sv-job:
    type: boolean
    default: false
  lang-ta-job:
    type: boolean
    default: false
  lang-tl-job:
    type: boolean
    default: false
  lang-uk-job:
    type: boolean
    default: false
  lang-zh-job:
    type: boolean
    default: false
  office-extension-job:
    type: boolean
    default: false
  rpm-package-job:
    type: boolean
    default: false
  server-job:
    type: boolean
    default: false
  standalone-job:
    type: boolean
    default: false
  tools-job: 
    type: boolean
    default: false
  wikipedia-job:
    type: boolean
    default: false
workflows:
  full:
    when: << pipeline.parameters.full-job >>
    jobs:
      - test-and-deploy-full
  commandline:
    when: << pipeline.parameters.commandline-job >>
    jobs:
      - test-deploy-module:
jobs:  
  test-deploy-module:
    resource_class: medium
    executor:
      name: docker-openjdk8
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - test-and-deploy-module
#      - mvn clean package -pl << parameters.module >>
#      - mvn -s .circleci.settings.xml deploy -DskipTests
commands:
  test-and-deploy-module:
    description: Test and deploy all changed modules
  steps:
    -run: .circleci/test-and-deploy-modules.sh << pipeline.parameters >>
    
  
  
  