version: 2.1

parameters:
  run_all_tests:
    type: boolean
    default: false
  run_lang_ar_tests:
    type: boolean
    default: false
  run_lang_ast_tests:
    type: boolean
    default: false
  run_lang_be_tests:
    type: boolean
    default: false
  run_lang_de_tests:
    type: boolean
    default: false

commands:
  # Run tests
  run-tests:
    description: run tests
    parameters:
      projects:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn install -DskipTests
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn --projects <<parameters.projects>> clean test
  check-dir:
    description: test directory
    steps:
      - run: pwd

executors:
  docker-openjdk8:
    docker:
      - image: circleci/openjdk:8-jdk

workflows:
  test-all:
    when: << pipeline.parameters.run_all_tests >>
    jobs:
      - test-all-job
  test-lang-de:
    when: << pipeline.parameters.run_lang_be_tests >>
    jobs:
      - test-lang-de-job
jobs:
  test-all-job:
    executor:
      name: docker-openjdk8
    working_directory: ~/repo
    steps:
      - check-dir
      #- run-tests:
      #projects: languagetool-commandline
  test-lang-de-job:
    executor:
      name: docker-openjdk8
    working_directory: ~/repo
    steps:
      - run-tests:
          projects: languagetool-language-modules/de
