version: 2.1
parameters:
  commandline_changed:
    type: boolean
    default: false
  core_changed:
    type: boolean
    default: false
  dev_changed:
    type: boolean
    default: false
  gui-commons_changed:
    type: boolean
    default: false
  http-client_changed:
    type: boolean
    default: false
  lang-ar_changed:
    type: boolean
    default: false
  lang-ast_changed:
    type: boolean
    default: false
  lang-be_changed:
    type: boolean
    default: false
  lang-de_changed:
    type: boolean
    default: false
commands:
  run-tests:
    description: run tests
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn install -DskipTests
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean test

executors:
  docker-openjdk8:
    docker:
      - image: circleci/openjdk:8-jdk

workflows:
  test-commandline:
    when: << pipeline.parameters.commandline_changed >>
    jobs:
      - test-commandline-job
  test-lang-de:
    when: << pipeline.parameters.lang-de_changed >>
    jobs:
      - test-lang-de-job
jobs:
  test-commandline-job:
    executor:
      name: docker-openjdk8
    working_directory: ~/repo/languagetool-commandline
    steps:
      - run-tests
  test-lang-de-job:
    executor:
      name: docker-openjdk8
    working_directory: ~/repo/languagetool-language-modules/de
      steps:
        - run-tests
