version: 2.1

jobs:
  test:
    parameters:
      path:
        type: string
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo/<<parameters.path>>
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn install -DskipTests
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean test

parameters:
  commandline_changed:
    type: boolean
    default: false
  core_changed:
    type: boolean
    default: false
  dev_changed:
    type: boolean
    default: false
  gui-commons_changed:
    type: boolean
    default: false
  http-client_changed:
    type: boolean
    default: false
  lang-ar_changed:
    type: boolean
    default: false
  lang-ast_changed:
    type: boolean
    default: false
  lang-be_changed:
    type: boolean
    default: false

workflows:
  test-commandline:
    when: << pipeline.parameters.commandline_changed >>
    jobs:
      - test:
          - path: languagetool-commandline
  test-core:
    when: << pipeline.parameters.core_changed >>
    jobs:
      - test:
          - path: languagetool-core
